export function createNavigationState({
  getActivePage, setActivePage, getActiveFilter,
  getActiveSecretAlbumId, setActiveSecretAlbumId,
  getActiveSecretFolderId, setActiveSecretFolderId,
  getSecretSelectionMode, setSecretSelectionMode,
  getSelectedSecretImageIndexes, getSession, getCloudDb,
  getPendingNewPhotos, getSecretItems, getLastSecretSyncAt,
  getFilteredPhotoCount, getPhotos, getWishes, getRecipes, getActiveDialogPhoto,
  getAccountDataState, getWeekendCloudAvailable,
}) {
  return {
    get activePage() { return getActivePage(); },
    set activePage(value) { setActivePage(value); },
    get activeFilter() { return getActiveFilter(); },
    get activeSecretAlbumId() { return getActiveSecretAlbumId(); },
    set activeSecretAlbumId(value) { setActiveSecretAlbumId(value); },
    get activeSecretFolderId() { return getActiveSecretFolderId(); },
    set activeSecretFolderId(value) { setActiveSecretFolderId(value); },
    get secretSelectionMode() { return getSecretSelectionMode(); },
    set secretSelectionMode(value) { setSecretSelectionMode(value); },
    get selectedSecretImageIndexes() { return getSelectedSecretImageIndexes(); },
    get session() { return getSession(); },
    get cloudDb() { return getCloudDb(); },
    get pendingNewPhotos() { return getPendingNewPhotos(); },
    get secretItems() { return getSecretItems(); },
    get lastSecretSyncAt() { return getLastSecretSyncAt(); },
    get filteredPhotoCount() { return getFilteredPhotoCount(); },
    get photos() { return getPhotos(); },
    get wishes() { return getWishes(); },
    get recipes() { return getRecipes(); },
    get accountDataState() { return getAccountDataState(); },
    get weekendCloudAvailable() { return getWeekendCloudAvailable(); },
    get activeDialogPhoto() { return getActiveDialogPhoto(); },
  };
}

export function createSessionState({
  getCloudDb, setCloudDb, getSession, setSession, getSyncedUserId, setSyncedUserId,
  getAccountProfile, setAccountProfile, getActiveVipLevel, setActiveVipLevel,
  getRecipes, setRecipes, getWishes, setWishes, getShoppingItems, setShoppingItems,
  getWeekendPlans, setWeekendPlans, getAnniversaries, setAnniversaries,
  getAccountDataState, setAccountDataState, getActivePage,
  getCloudSyncAvailable, setCloudSyncAvailable, getWeekendCloudAvailable, setWeekendCloudAvailable,
  getAnniversaryCloudAvailable, setAnniversaryCloudAvailable,
  getPhotoFlagsCloudAvailable, setPhotoFlagsCloudAvailable, getSecretCloudAvailable, setSecretCloudAvailable,
  getFoodOptionsCloudAvailable, setFoodOptionsCloudAvailable,
  getProfilePreferencesCloudAvailable, setProfilePreferencesCloudAvailable,
  getThanksColorCloudAvailable, setThanksColorCloudAvailable,
  getGratitudeNotes, setGratitudeNotes, getSecretItems, setSecretItems,
  getSecretFolders, setSecretFolders,
  getSecretDefaultFolderId, setSecretDefaultFolderId, getSecretAlbumContextMenu, setSecretAlbumContextMenu,
  getNotifications, setNotifications, getCommentReplyToId, setCommentReplyToId,
  getFamilyInfo, setFamilyInfo, getFamilyMembers, setFamilyMembers,
  getFamilyInvitations, setFamilyInvitations, getFamilyMemberMap, setFamilyMemberMap,
  getPhotoComments, setPhotoComments, getActiveDialogPhoto, setActiveDialogPhoto,
  getCloudSyncInFlight, setCloudSyncInFlight,
}) {
  return {
    get cloudDb() { return getCloudDb(); }, set cloudDb(value) { setCloudDb(value); },
    get session() { return getSession(); }, set session(value) { setSession(value); },
    get syncedUserId() { return getSyncedUserId(); }, set syncedUserId(value) { setSyncedUserId(value); },
    get accountProfile() { return getAccountProfile(); }, set accountProfile(value) { setAccountProfile(value); },
    get activeVipLevel() { return getActiveVipLevel(); }, set activeVipLevel(value) { setActiveVipLevel(value); },
    get recipes() { return getRecipes(); }, set recipes(value) { setRecipes(value); },
    get wishes() { return getWishes(); }, set wishes(value) { setWishes(value); },
    get shoppingItems() { return getShoppingItems(); }, set shoppingItems(value) { setShoppingItems(value); },
    get weekendPlans() { return getWeekendPlans(); }, set weekendPlans(value) { setWeekendPlans(value); },
    get anniversaries() { return getAnniversaries(); }, set anniversaries(value) { setAnniversaries(value); },
    get accountDataState() { return getAccountDataState(); }, set accountDataState(value) { setAccountDataState(value); },
    get activePage() { return getActivePage(); },
    get cloudSyncAvailable() { return getCloudSyncAvailable(); }, set cloudSyncAvailable(value) { setCloudSyncAvailable(value); },
    get weekendCloudAvailable() { return getWeekendCloudAvailable(); }, set weekendCloudAvailable(value) { setWeekendCloudAvailable(value); },
    get anniversaryCloudAvailable() { return getAnniversaryCloudAvailable(); }, set anniversaryCloudAvailable(value) { setAnniversaryCloudAvailable(value); },
    get photoFlagsCloudAvailable() { return getPhotoFlagsCloudAvailable(); }, set photoFlagsCloudAvailable(value) { setPhotoFlagsCloudAvailable(value); },
    get secretCloudAvailable() { return getSecretCloudAvailable(); }, set secretCloudAvailable(value) { setSecretCloudAvailable(value); },
    get foodOptionsCloudAvailable() { return getFoodOptionsCloudAvailable(); }, set foodOptionsCloudAvailable(value) { setFoodOptionsCloudAvailable(value); },
    get profilePreferencesCloudAvailable() { return getProfilePreferencesCloudAvailable(); }, set profilePreferencesCloudAvailable(value) { setProfilePreferencesCloudAvailable(value); },
    get thanksColorCloudAvailable() { return getThanksColorCloudAvailable(); }, set thanksColorCloudAvailable(value) { setThanksColorCloudAvailable(value); },
    get gratitudeNotes() { return getGratitudeNotes(); }, set gratitudeNotes(value) { setGratitudeNotes(value); },
    get secretItems() { return getSecretItems(); }, set secretItems(value) { setSecretItems(value); },
    get secretFolders() { return getSecretFolders(); }, set secretFolders(value) { setSecretFolders(value); },
    get secretDefaultFolderId() { return getSecretDefaultFolderId(); }, set secretDefaultFolderId(value) { setSecretDefaultFolderId(value); },
    get secretAlbumContextMenu() { return getSecretAlbumContextMenu(); }, set secretAlbumContextMenu(value) { setSecretAlbumContextMenu(value); },
    get notifications() { return getNotifications(); }, set notifications(value) { setNotifications(value); },
    get commentReplyToId() { return getCommentReplyToId(); }, set commentReplyToId(value) { setCommentReplyToId(value); },
    get familyInfo() { return getFamilyInfo(); }, set familyInfo(value) { setFamilyInfo(value); },
    get familyMembers() { return getFamilyMembers(); }, set familyMembers(value) { setFamilyMembers(value); },
    get familyInvitations() { return getFamilyInvitations(); }, set familyInvitations(value) { setFamilyInvitations(value); },
    get familyMemberMap() { return getFamilyMemberMap(); }, set familyMemberMap(value) { setFamilyMemberMap(value); },
    get photoComments() { return getPhotoComments(); }, set photoComments(value) { setPhotoComments(value); },
    get activeDialogPhoto() { return getActiveDialogPhoto(); }, set activeDialogPhoto(value) { setActiveDialogPhoto(value); },
    get cloudSyncInFlight() { return getCloudSyncInFlight(); }, set cloudSyncInFlight(value) { setCloudSyncInFlight(value); },
  };
}
