name = "life-vlog-r2-upload"
main = "src/worker.js"
compatibility_date = "2026-07-02"
account_id = "e91104ac5162a3cb66f045e5b45f0bdb"
workers_dev = true
preview_urls = false

[triggers]
crons = ["20 18 * * *"]

[vars]
PUBLIC_R2_URL = "https://pub-47959f26cde042c3b37bc0f8f3f441ce.r2.dev"
ALLOWED_ORIGINS = "https://life-vlog-site.pages.dev,https://xiudan320-ship-it.github.io,http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000,http://127.0.0.1:4175"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "life-vlog-photos"

[[d1_databases]]
binding = "DB"
database_name = "life-vlog-db"
database_id = "71b8a86d-5129-44a7-be04-9b2423fb000f"
