export function createRouteControllerOptions({
  elements,
  state,
  services,
  config,
  core,
  feature,
  pages,
}) {
  const {
    secretRepository,
    secretDataService,
    wardrobeRepository,
    householdRepository,
    diaryRepository,
    mediaCacheService,
    cloudflareBackend,
    assetController,
  } = services;
  const {
    secretActions,
    familySettingsActions,
    dataSafetyActions,
    trashActions,
    diaryComposerActions,
    offlineCacheActions,
    anniversaryActions,
  } = feature;
  const {
    secretController,
    recipeController,
    wishlistController,
    weekendController,
    dataSafetyController,
    callLoaded,
  } = pages;
  const {
    secretState,
    getSecretDefaultFolderId,
    setSecretDefaultFolderId,
    getSortedPhotos,
    getDisplayTitle,
    getPlainNote,
    isMissingCloudSchema,
    openPhoto,
    showPhotoDialogPreservingScroll,
    renderDialogMedia,
    fitSecretViewerImage,
    refreshDiaryViewerToolbar,
    refreshSecretViewerToolbar,
    resetSecretImageZoom,
    setSecretViewerStatus,
    updateSecretToolbarTop,
    getAuthorName,
    uploadImageFile,
    slugify,
    copyUrlToR2,
    deleteR2Object,
    confirmAction,
    awardExperience,
    normalizeUuid,
    escapeHtml,
    getSessionDisplayName,
    renderOverview,
    renderFoodWheel,
    renderSettingsToolOrderPanel,
    renderSettingsSummary,
    loadFamilyLevelProfiles,
    loadPhotos,
    synchronizeWeekendPlans,
    loadGratitudeNotes,
    loadFamilyContext,
    getPhotoImages,
    normalizeSecretImages,
    formatDate,
    formatFileSize,
    openWishImage,
    openWeekendImageGallery,
    getClipboardImageUrl,
    setGlobalStatus,
    setSecretStatus,
    showMiniToast,
    dismissMiniToast,
    isMobileViewport,
    renderWeekendReminderNotice,
  } = core;
  const {
    renderCachedSecretItems,
    saveSecretItemsCache,
    loadCacheCapacityMb,
    saveCacheCapacityMb,
    scheduleOfflineMediaCache,
    loadMediaCachePolicy,
    saveMediaCachePolicy,
    collectSecretOfflineMediaUrls,
    collectDiaryOfflineMediaUrls,
    cacheOfflineMedia,
    refreshCacheInfo,
    getAppCacheStats: getFeatureCacheStats,
  } = offlineCacheActions;
  const {
    renderAnniversaries,
    synchronizeAnniversaries,
  } = anniversaryActions;
  const {
    renderFamilyDialog,
    openSettingsChildDialog,
    setActiveSettingsSection,
  } = familySettingsActions;
  const {
    renderCloudBackups,
    renderTrashItems,
    runOfflineDiagnostics,
    renderUploadCenter,
  } = dataSafetyActions;
  const {
    createTrashItem,
    rollbackTrashItem,
    confirmWishDeletion,
    loadTrashItems,
    restoreTrashItem,
    permanentlyDeleteTrashItem,
    getTrashOwnershipLabel,
  } = trashActions;
  const {
    getQueuedDiaryUploads,
    isDiaryUploadQueueProcessing,
    removeQueuedDiaryUpload,
    processDiaryUploadQueue,
  } = diaryComposerActions;
  const { refreshPushSettings } = feature.pushActions;
  const {
    getImageFilesFromClipboard,
  } = secretActions;
  const {
    createClient: createCloudflareClient,
    request: cloudflareRequest,
  } = cloudflareBackend;
  const renderRecipes = (...args) => callLoaded(recipeController, "render", ...args);
  const renderWishes = (...args) => callLoaded(wishlistController, "render", ...args);
  const renderWeekendPlans = (...args) => callLoaded(weekendController, "render", ...args);
  const renderShopping = (...args) => callLoaded(pages.shoppingController, "render", ...args);
  return buildRouteControllerOptions({
    elements,
    secretState,
    secretRepository,
    secretDataService,
    assetController,
    albumImageLimit: config.albumImageLimit,
    allFolderId: config.secretAllFolderId,
    favoritesFolderId: config.secretFavoritesFolderId,
    mobileDialogBreakpoint: config.mobileDialogBreakpoint,
    getSecretDefaultFolderId,
    setSecretDefaultFolderId,
    saveSecretItemsCache,
    renderCachedSecretItems,
    setGlobalStatus,
    setSecretStatus,
    showMiniToast,
    dismissMiniToast,
    isMobileViewport,
    getSortedPhotos,
    getDisplayTitle,
    getPlainNote,
    isMissingCloudSchema,
    openPhoto,
    createTrashItem,
    rollbackTrashItem,
    showPhotoDialogPreservingScroll,
    renderDialogMedia,
    fitSecretViewerImage,
    refreshDiaryViewerToolbar,
    refreshSecretViewerToolbar,
    resetSecretImageZoom,
    setSecretViewerStatus,
    updateSecretToolbarTop,
    wardrobeRepository,
    getSession: () => state.session,
    getFamilyMembers: () => state.familyMembers.map((member) => ({ ...member, username: getAuthorName(member.user_id) })),
    getAuthorName,
    uploadImageFile,
    slugify,
    copyUrlToR2,
    deleteR2Object,
    confirmAction,
    awardExperience,
    normalizeUuid,
    escapeHtml,
    recipesKey: config.recipesKey,
    householdRepository,
    getSessionDisplayName,
    getRecipes: () => state.recipes,
    setRecipes: (items) => { state.recipes = items; },
    canSync: () => state.cloudSyncAvailable,
    canManageItem: core.canManageItem,
    getClipboardFiles: getImageFilesFromClipboard,
    getClipboardImageUrl,
    compressImage: core.compressImage,
    uploadToR2: core.uploadToR2,
    renderOverview,
    renderFoodWheel,
    getDatabase: () => state.cloudDb,
    getWishes: () => state.wishes,
    setWishes: (items) => { state.wishes = items; },
    getActiveWishView: () => state.activeWishView,
    setActiveWishView: (view) => { state.activeWishView = view; },
    getDataState: () => state.accountDataState,
    extractImageUrls: core.extractImageUrls,
    cleanupStoredImagePaths: core.cleanupStoredImagePaths,
    formatFileSize,
    openWishImage,
    confirmWishDeletion,
    showToast: showMiniToast,
    getShoppingItems: () => state.shoppingItems,
    setShoppingItems: (items) => { state.shoppingItems = items; },
    getActiveShoppingFilter: () => state.activeShoppingFilter,
    setActiveShoppingFilter: (filter) => {
      state.activeShoppingFilter = ["open", "done"].includes(filter) ? filter : "open";
    },
    weekendKey: config.weekendKey,
    getWeekendPlans: () => state.weekendPlans,
    setWeekendPlans: (items) => { state.weekendPlans = items; },
    weekendCanSync: () => state.weekendCloudAvailable,
    formatDate,
    renderReminder: renderWeekendReminderNotice,
    openWeekendImageGallery,
    familySettingsState: feature.familySettingsState,
    r2UploadEndpoint: config.r2UploadEndpoint,
    renderAvatarMarkup: core.renderAvatarMarkup,
    renderSettingsToolOrderPanel,
    refreshPushSettings,
    renderCloudBackups,
    renderTrashItems,
    runOfflineDiagnostics,
    renderUploadCenter,
    renderSettingsSummary,
    refreshCacheInfo,
    loadFamilyLevelProfiles,
    loadPhotos,
    synchronizeWeekendPlans,
    synchronizeAnniversaries,
    loadGratitudeNotes,
    renderRecipes,
    renderWishes,
    renderWeekendPlans,
    renderAnniversaries,
    loadFamilyContext,
    defaultDiaryCacheMb: config.defaultDiaryCacheMb,
    defaultSecretCacheMb: config.defaultSecretCacheMb,
    minCacheMb: config.minCacheMb,
    maxCacheMb: config.maxCacheMb,
    secretMediaCacheName: config.secretMediaCacheName,
    diaryMediaCacheName: config.diaryMediaCacheName,
    secretItemsCacheKey: config.secretItemsCacheKey,
    photoFeedCacheKey: config.photoFeedCacheKey,
    mediaCacheService,
    getUserId: () => state.session?.user?.id,
    loadCacheCapacityMb,
    saveCacheCapacityMb,
    scheduleOfflineMediaCache,
    configureCacheManagementUi: core.configureCacheManagementUi,
    setActiveSettingsSection,
    loadMediaCachePolicy,
    saveMediaCachePolicy,
    collectSecretOfflineMediaUrls,
    collectDiaryOfflineMediaUrls,
    cacheOfflineMedia,
    openSettingsChildDialog,
    dataSafetyState: feature.dataSafetyState,
    cloudflareRequest,
    getLocalDateKey: core.getLocalDateKey,
    loadTrashItems,
    restoreTrashItem,
    permanentlyDeleteTrashItem,
    getTrashOwnershipLabel,
    diaryRepository,
    normalizeSecretImages,
    getQueuedDiaryUploads,
    isDiaryUploadQueueProcessing,
    removeQueuedDiaryUpload,
    processDiaryUploadQueue,
    getPhotoImages,
    getAppCacheStats: getFeatureCacheStats,
    secretController,
    recipeController,
    wishlistController,
    weekendController,
    dataSafetyController,
    callLoaded,
  });
}

function buildRouteControllerOptions({
  elements,
  secretState,
  secretRepository,
  secretDataService,
  assetController,
  albumImageLimit,
  allFolderId,
  favoritesFolderId,
  mobileDialogBreakpoint,
  getSecretDefaultFolderId,
  setSecretDefaultFolderId,
  saveSecretItemsCache,
  renderCachedSecretItems,
  setGlobalStatus,
  setSecretStatus,
  showMiniToast,
  dismissMiniToast,
  isMobileViewport,
  getSortedPhotos,
  getDisplayTitle,
  getPlainNote,
  isMissingCloudSchema,
  openPhoto,
  createTrashItem,
  rollbackTrashItem,
  showPhotoDialogPreservingScroll,
  renderDialogMedia,
  fitSecretViewerImage,
  refreshDiaryViewerToolbar,
  refreshSecretViewerToolbar,
  resetSecretImageZoom,
  setSecretViewerStatus,
  updateSecretToolbarTop,
  wardrobeRepository,
  getSession,
  getFamilyMembers,
  getAuthorName,
  uploadImageFile,
  slugify,
  copyUrlToR2,
  deleteR2Object,
  confirmAction,
  awardExperience,
  normalizeUuid,
  escapeHtml,
  recipesKey,
  householdRepository,
  getSessionDisplayName,
  getRecipes,
  setRecipes,
  canSync,
  canManageItem,
  getClipboardFiles,
  getClipboardImageUrl,
  compressImage,
  uploadToR2,
  renderOverview,
  renderFoodWheel,
  getDatabase,
  getWishes,
  setWishes,
  getActiveWishView,
  setActiveWishView,
  getDataState,
  extractImageUrls,
  cleanupStoredImagePaths,
  formatFileSize,
  openWishImage,
  confirmWishDeletion,
  showToast,
  getShoppingItems,
  setShoppingItems,
  getActiveShoppingFilter,
  setActiveShoppingFilter,
  weekendKey,
  getWeekendPlans,
  setWeekendPlans,
  weekendCanSync,
  formatDate,
  renderReminder,
  openWeekendImageGallery,
  familySettingsState,
  r2UploadEndpoint,
  renderAvatarMarkup,
  renderSettingsToolOrderPanel,
  refreshPushSettings,
  renderCloudBackups,
  renderTrashItems,
  runOfflineDiagnostics,
  renderUploadCenter,
  renderSettingsSummary,
  refreshCacheInfo,
  loadFamilyLevelProfiles,
  loadPhotos,
  synchronizeWeekendPlans,
  synchronizeAnniversaries,
  loadGratitudeNotes,
  renderRecipes,
  renderWishes,
  renderWeekendPlans,
  renderAnniversaries,
  loadFamilyContext,
  defaultDiaryCacheMb,
  defaultSecretCacheMb,
  minCacheMb,
  maxCacheMb,
  secretMediaCacheName,
  diaryMediaCacheName,
  secretItemsCacheKey,
  photoFeedCacheKey,
  mediaCacheService,
  getUserId,
  loadCacheCapacityMb,
  saveCacheCapacityMb,
  scheduleOfflineMediaCache,
  configureCacheManagementUi,
  setActiveSettingsSection,
  loadMediaCachePolicy,
  saveMediaCachePolicy,
  collectSecretOfflineMediaUrls,
  collectDiaryOfflineMediaUrls,
  cacheOfflineMedia,
  openSettingsChildDialog,
  dataSafetyState,
  cloudflareRequest,
  getLocalDateKey,
  loadTrashItems,
  restoreTrashItem,
  permanentlyDeleteTrashItem,
  getTrashOwnershipLabel,
  diaryRepository,
  normalizeSecretImages,
  getQueuedDiaryUploads,
  isDiaryUploadQueueProcessing,
  removeQueuedDiaryUpload,
  processDiaryUploadQueue,
  getPhotoImages,
  getAppCacheStats,
  secretController,
  recipeController,
  wishlistController,
  weekendController,
  dataSafetyController,
  callLoaded,
}) {
  return {
    secret: {
      elements,
      state: secretState,
      repository: secretRepository,
      dataService: secretDataService,
      assets: assetController,
      albumImageLimit,
      allFolderId,
      favoritesFolderId,
      mobileDialogBreakpoint,
      getSecretDefaultFolderId,
      setSecretDefaultFolderId,
      saveSecretItemsCache: (...args) => saveSecretItemsCache(...args),
      renderCachedSecretItems: (...args) => renderCachedSecretItems(...args),
      setGlobalStatus,
      setSecretStatus,
      showMiniToast,
      dismissMiniToast,
      isMobileViewport,
      getSortedPhotos,
      getDisplayTitle,
      getPlainNote,
      isMissingCloudSchema,
      openPhoto,
      createTrashItem,
      rollbackTrashItem,
      showPhotoDialogPreservingScroll,
      renderDialogMedia,
      fitSecretViewerImage,
      refreshDiaryViewerToolbar,
      refreshSecretViewerToolbar,
      resetSecretImageZoom,
      setSecretViewerStatus,
      updateSecretToolbarTop,
    },
    wardrobe: {
      root: elements.wardrobeRoot,
      repository: wardrobeRepository,
      getSession,
      getFamilyMembers,
      uploadFile: (file, safeName, index, total, statusSetter) => uploadImageFile(
        file, slugify(safeName), index, total, { folder: "wardrobe", statusSetter, thumbnail: true }
      ),
      importUrl: (url, safeName) => copyUrlToR2(url, slugify(safeName), "wardrobe"),
      deleteAsset: (path) => deleteR2Object(path),
      confirmAction,
      notify: showMiniToast,
      onExperience: (action) => awardExperience(action),
    },
    recipe: {
      elements,
      storageKey: recipesKey,
      repository: householdRepository,
      getSession,
      getDisplayName: getSessionDisplayName,
      getRecipes,
      setRecipes,
      canSync,
      getAuthorName,
      canManageItem,
      normalizeUuid,
      getClipboardFiles,
      getClipboardImageUrl,
      copyUrlToR2,
      compressImage,
      uploadToR2,
      slugify,
      awardExperience,
      renderOverview,
      renderFoodWheel,
      confirmAction,
      createTrashItem,
      rollbackTrashItem,
    },
    wishlist: {
      elements,
      repository: householdRepository,
      getSession,
      getDatabase,
      getWishes,
      setWishes,
      getActiveView: getActiveWishView,
      setActiveView: setActiveWishView,
      getDataState,
      canSync,
      getAuthorName,
      canManageItem,
      normalizeUuid,
      extractImageUrls,
      getClipboardImageUrl,
      copyUrlToR2,
      compressImage,
      uploadToR2,
      cleanupStoredImagePaths,
      slugify,
      formatFileSize,
      awardExperience,
      renderOverview,
      openWishImage,
      escapeHtml,
      confirmAction,
      confirmWishDeletion,
      createTrashItem,
      rollbackTrashItem,
      showToast,
    },
    shopping: {
      elements,
      repository: householdRepository,
      getSession,
      getDatabase,
      getItems: getShoppingItems,
      setItems: setShoppingItems,
      getActiveFilter: getActiveShoppingFilter,
      setActiveFilter: setActiveShoppingFilter,
      getDataState,
      canSync,
      canManageItem,
      normalizeUuid,
      compressImage,
      uploadToR2,
      cleanupStoredImagePaths,
      slugify,
      formatFileSize,
      escapeHtml,
      confirmAction,
      showToast,
    },
    wishlistHub: { elements },
    weekend: {
      elements,
      storageKey: weekendKey,
      repository: householdRepository,
      getSession,
      getDisplayName: getSessionDisplayName,
      getPlans: getWeekendPlans,
      setPlans: setWeekendPlans,
      canSync: weekendCanSync,
      getAuthorName,
      canManageItem,
      getClipboardFiles,
      getClipboardImageUrl,
      extractImageUrls,
      escapeHtml,
      formatDate,
      slugify,
      normalizeUuid,
      uploadImageFile,
      copyUrlToR2,
      cleanupStoredImagePaths,
      awardExperience,
      renderReminder,
      openGallery: openWeekendImageGallery,
      confirmAction,
      createTrashItem,
      rollbackTrashItem,
    },
    settings: {
      familySettings: {
        elements,
        state: familySettingsState,
        r2UploadEndpoint,
        householdRepository,
        renderAvatarMarkup,
        renderSettingsToolOrderPanel,
        refreshPushSettings: (...args) => refreshPushSettings(...args),
        renderCloudBackups: (...args) => callLoaded(dataSafetyController, "renderCloudBackups", ...args),
        renderTrashItems: (...args) => callLoaded(dataSafetyController, "renderTrashItems", ...args),
        runOfflineDiagnostics: (...args) => callLoaded(dataSafetyController, "runOfflineDiagnostics", ...args),
        renderUploadCenter: (...args) => callLoaded(dataSafetyController, "renderUploadCenter", ...args),
        renderSettingsSummary,
        refreshCacheInfo,
        loadFamilyLevelProfiles,
        loadPhotos,
        synchronizeWeekendPlans,
        synchronizeAnniversaries: (...args) => synchronizeAnniversaries(...args),
        loadGratitudeNotes,
        loadSecretItems: (...args) => secretDataService.load(...args),
        renderRecipes: (...args) => callLoaded(recipeController, "render", ...args),
        renderWishes: (...args) => callLoaded(wishlistController, "render", ...args),
        renderWeekendPlans: (...args) => callLoaded(weekendController, "render", ...args),
        renderAnniversaries: (...args) => renderAnniversaries(...args),
        isMissingCloudSchema,
        loadFamilyContext,
      },
      offlineSettings: {
        elements,
        constants: {
          defaultDiaryCacheMb,
          defaultSecretCacheMb,
          minCacheMb,
          maxCacheMb,
          secretMediaCacheName,
          diaryMediaCacheName,
          secretItemsCacheKey,
          photoFeedCacheKey,
        },
        mediaCacheService,
        getUserId,
        loadCacheCapacityMb,
        saveCacheCapacityMb,
        scheduleOfflineMediaCache,
        refreshCacheInfo,
        renderSettingsSummary,
        configureCacheManagementUi,
        setActiveSettingsSection,
        loadMediaCachePolicy,
        saveMediaCachePolicy,
        showMiniToast,
        dismissMiniToast,
        collectSecretOfflineMediaUrls,
        collectDiaryOfflineMediaUrls,
        cacheOfflineMedia,
        formatFileSize,
        openSettingsChildDialog,
      },
      dataSafety: {
        elements,
        state: dataSafetyState,
        r2UploadEndpoint,
        cloudflareRequest,
        getLocalDateKey,
        showMiniToast,
        dismissMiniToast,
        loadTrashItems,
        restoreTrashItem,
        permanentlyDeleteTrashItem,
        getTrashOwnershipLabel,
        compressImage,
        uploadToR2,
        getPhotoImages,
        getPlainNote,
        diaryRepository,
        normalizeSecretImages,
        secretRepository,
        loadPhotos,
        loadSecretItems: (...args) => secretDataService.load(...args),
        setActiveSettingsSection,
        mediaCacheService,
        getAppCacheStats,
        collectDiaryOfflineMediaUrls,
        collectSecretOfflineMediaUrls,
        getQueuedDiaryUploads,
        isDiaryUploadQueueProcessing,
        removeQueuedDiaryUpload,
        processDiaryUploadQueue,
      },
    },
  };
}
