export const TABLE_CONFIG = {
  user_profiles: {
    columns: [
      "user_id",
      "username",
      "recharge_total",
      "vip_level",
      "experience_total",
      "last_login_date",
      "login_streak",
      "today_experience_date",
      "today_experience_amount",
      "theme_preference",
      "home_name",
      "secret_default_folder_id",
      "food_options",
      "preferred_thanks_color",
      "avatar_url",
      "avatar_path",
      "created_at",
      "updated_at",
    ],
    scope: "family",
    writeScope: "own",
    ownerColumn: "user_id",
    jsonColumns: ["food_options"],
  },
  photos: {
    columns: [
      "id",
      "user_id",
      "title",
      "note",
      "category",
      "taken_at",
      "is_public",
      "image_path",
      "image_url",
      "width",
      "height",
      "is_featured",
      "is_pinned",
      "created_at",
      "updated_at",
    ],
    scope: "family",
    writeScope: "own",
    ownerColumn: "user_id",
    booleanColumns: ["is_public", "is_featured", "is_pinned"],
  },
  mood_diaries: {
    columns: ["id", "user_id", "diary_date", "mood", "content", "tags", "created_at", "updated_at"],
    scope: "family",
    writeScope: "own",
    ownerColumn: "user_id",
    jsonColumns: ["tags"],
    conflictColumns: ["user_id", "diary_date"],
  },
  photo_favorites: {
    columns: ["user_id", "photo_id", "created_at"],
    scope: "own",
    writeScope: "own",
    ownerColumn: "user_id",
    conflictColumns: ["user_id", "photo_id"],
  },
  photo_comments: {
    columns: ["id", "photo_id", "user_id", "parent_id", "body", "created_at", "updated_at"],
    scope: "comments",
    writeScope: "own",
    ownerColumn: "user_id",
  },
  recipes: {
    columns: [
      "id",
      "user_id",
      "name",
      "category",
      "cooking_time",
      "servings",
      "cover_image",
      "seasonings",
      "ingredients",
      "steps",
      "note",
      "created_at",
      "updated_at",
    ],
    scope: "family",
    ownerColumn: "user_id",
    jsonColumns: ["seasonings", "ingredients", "steps"],
  },
  wishes: {
    columns: [
      "id",
      "user_id",
      "title",
      "wish_type",
      "planned_date",
      "priority",
      "note",
      "completion_note",
      "is_done",
      "completed_at",
      "sort_order",
      "created_at",
      "updated_at",
    ],
    scope: "family",
    ownerColumn: "user_id",
    booleanColumns: ["is_done"],
  },
  shopping_items: {
    columns: [
      "id",
      "user_id",
      "name",
      "image_url",
      "image_path",
      "price",
      "product_link",
      "note",
      "is_completed",
      "completed_at",
      "sort_order",
      "created_at",
      "updated_at",
    ],
    scope: "family",
    ownerColumn: "user_id",
    booleanColumns: ["is_completed"],
  },
  weekend_plans: {
    columns: [
      "id",
      "user_id",
      "title",
      "plan_date",
      "location",
      "plan_type",
      "note",
      "is_done",
      "created_at",
      "updated_at",
    ],
    scope: "family",
    ownerColumn: "user_id",
    booleanColumns: ["is_done"],
  },
  wardrobe_locations: {
    columns: ["id", "user_id", "name", "note", "sort_order", "created_at", "updated_at"],
    scope: "family",
    ownerColumn: "user_id",
  },
  wardrobe_items: {
    columns: [
      "id",
      "user_id",
      "wearer_user_id",
      "name",
      "item_type",
      "category",
      "description",
      "fit_note",
      "location_id",
      "status",
      "seasons",
      "occasions",
      "style_tags",
      "color_tags",
      "images",
      "is_favorite",
      "wear_count",
      "last_worn_at",
      "created_at",
      "updated_at",
    ],
    scope: "family",
    ownerColumn: "user_id",
    jsonColumns: ["seasons", "occasions", "style_tags", "color_tags", "images"],
    booleanColumns: ["is_favorite"],
  },
  wardrobe_wear_logs: {
    columns: ["id", "user_id", "wardrobe_item_id", "worn_on", "note", "created_at"],
    scope: "family",
    ownerColumn: "user_id",
  },
  anniversaries: {
    columns: ["id", "user_id", "title", "event_type", "event_date", "note", "created_at", "updated_at"],
    scope: "family",
    ownerColumn: "user_id",
  },
  gratitude_notes: {
    columns: ["id", "user_id", "body", "text_color", "created_at", "updated_at"],
    scope: "family",
    ownerColumn: "user_id",
  },
  notifications: {
    columns: ["id", "user_id", "actor_id", "type", "photo_id", "comment_id", "body", "is_read", "created_at"],
    scope: "own",
    writeScope: "own",
    ownerColumn: "user_id",
    booleanColumns: ["is_read"],
  },
  secret_items: {
    columns: ["id", "user_id", "folder_id", "title", "category", "note", "cover_image", "cover_path", "images", "linked_photo_id", "photo_sort_descending", "is_pinned", "sort_order", "created_at", "updated_at"],
    scope: "own",
    writeScope: "own",
    ownerColumn: "user_id",
    jsonColumns: ["images"],
    booleanColumns: ["is_pinned"],
  },
  secret_folders: {
    columns: ["id", "user_id", "name", "sort_order", "created_at", "updated_at"],
    scope: "own",
    writeScope: "own",
    ownerColumn: "user_id",
  },
  trash_items: {
    columns: ["id", "user_id", "item_type", "item_id", "label", "payload", "deleted_at", "expires_at"],
    scope: "own",
    writeScope: "own",
    ownerColumn: "user_id",
    jsonColumns: ["payload"],
  },
};
